# name: tag

# on:
#   push:
#     branches:
#       - main

# jobs:
#   tag:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           token: ${{ secrets.PAT }}
#       - name: "Tag current version"
#         id: autotag
#         uses: butlerlogic/action-autotag@stable
#         with:
#           GITHUB_TOKEN: ${{ secrets.PAT }}
#           strategy: package
#           tag_prefix: "v"
#           root: "/src/rewrite/spotiguess/package.json"